namespace AIVideoPlatform.Domain.Enums;

public enum JobStatus
{
    QUEUED, RESERVING_CREDITS, DOWNLOADING, ANALYZING, EXTRACTING_AUDIO, 
    SEPARATING_AUDIO, TRANSCRIBING, SEGMENT_ANALYSIS, TRANSLATING, 
    TRANSLATION_QA, GENERATING_TTS, FITTING_TTS, BUILDING_TIMELINE, 
    MIXING_AUDIO, GENERATING_SUBTITLE, RENDERING_VIDEO, VALIDATING_OUTPUT, 
    GENERATING_METADATA, UPLOADING_YOUTUBE, COMPLETED, FAILED, CANCELLED, REFUNDING
}

public enum StepStatus
{
    PENDING, RUNNING, COMPLETED, FAILED, CANCELLED
}

public enum TransactionType
{
    TOPUP, RESERVE, DEDUCT, REFUND
}
