<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AIVideoPlatform.Worker.Orchestrator-19589a4d-e0fe-4384-b7d5-a2c7553ab81c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIVideoPlatform.Application\AIVideoPlatform.Application.csproj" />
    <ProjectReference Include="..\AIVideoPlatform.Infrastructure\AIVideoPlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\AIVideoPlatform.Shared\AIVideoPlatform.Shared.csproj" />
  </ItemGroup>
</Project>
